export const BLOGS = [
    {
        title: "How the Modern Creator Economy Fuels Web Design Innovations",
        desc: "Organize your design system with clear, maintainable layers for better scalability.",
        image: "/images/blog1.jpeg",
        category: "Design System",
        author: "Sarah Leeman",
        authorRole: "Marketing Leader",
        authorCompany: "Mailchimp",
        authorCompanyUrl: "https://mailchimp.com",
        authorImage: "/images/creator1.jpg",
    },
    {
        title: "Build pages with Verve",
        desc: "Quickly create and launch pages using Verve’s intuitive builder and templates.",
        image: "/images/blog5.jpeg",
        category: "Verve Product",
        author: "John Doe",
        authorRole: "Product Manager",
        authorCompany: "Google",
        authorCompanyUrl: "https://google.com",
        authorImage: "/images/person-three.jpg",
    },
    {
        title: "The Rise of Virtual Influencers",
        desc: "The Rise of Virtual Influencers & What It Means for Brand Design.",
        image: "/images/blog3.jpeg",
        category: "AI",
        author: "Emily Johnson",
        authorRole: "Software Engineer",
        authorCompany: "Microsoft",
        authorCompanyUrl: "https://microsoft.com",
        authorImage: "/images/person-four.jpg",
    },
    {
        title: "Monetization This Season",
        desc: "Boost productivity with proven strategies for seamless team collaboration.",
        image: "/images/blog4.jpeg",
        category: "Productivity",
        author: "Michael Smith",
        authorRole: "UX Designer",
        authorCompany: "Adobe",
        authorCompanyUrl: "https://adobe.com",
        authorImage: "/images/person-five.jpg",
    },
];
