import { CreatorProfile } from "@/components/marketing/creator-profile"
import { notFound } from "next/navigation"

// Mock data - in a real app, this would come from a database
const creators = [
  {
    id: 1,
    name: "Sarah Johnson",
    username: "@sarahj_photo",
    category: "Photography",
    rating: 4.9,
    reviews: 127,
    avatar: "/images/creator1.jpg",
    coverImage: "/images/creator1.jpg",
    isVerified: true,
    location: "New York, USA",
    startingPrice: 150,
    tags: ["Portrait", "Wedding", "Commercial"],
    followers: "12.5K",
    following: "1.2K",
    bio: "Professional photographer with 8+ years of experience specializing in portrait, wedding, and commercial photography. I believe in capturing authentic moments that tell your unique story.",
    joinedDate: "March 2020",
    responseTime: "Within 2 hours",
    languages: ["English", "Spanish"],
    socialLinks: {
      instagram: "https://instagram.com/sarahj_photo",
      twitter: "https://twitter.com/sarahj_photo",
      website: "https://sarahjohnsonphoto.com",
      linkedin: "https://linkedin.com/in/sarahjohnson",
    },
    portfolio: [
      {
        id: 1,
        title: "Wedding Collection",
        image: "/placeholder.svg?height=300&width=400&text=Wedding+Photo",
        category: "Wedding",
        likes: 234,
        isLiked: false,
      },
      {
        id: 2,
        title: "Portrait Series",
        image: "/placeholder.svg?height=300&width=400&text=Portrait+Photo",
        category: "Portrait",
        likes: 189,
        isLiked: true,
      },
      {
        id: 3,
        title: "Commercial Work",
        image: "/placeholder.svg?height=300&width=400&text=Commercial+Photo",
        category: "Commercial",
        likes: 156,
        isLiked: false,
      },
      {
        id: 4,
        title: "Nature Photography",
        image: "/placeholder.svg?height=300&width=400&text=Nature+Photo",
        category: "Nature",
        likes: 298,
        isLiked: false,
      },
      {
        id: 5,
        title: "Event Coverage",
        image: "/placeholder.svg?height=300&width=400&text=Event+Photo",
        category: "Event",
        likes: 167,
        isLiked: true,
      },
      {
        id: 6,
        title: "Fashion Shoot",
        image: "/placeholder.svg?height=300&width=400&text=Fashion+Photo",
        category: "Fashion",
        likes: 312,
        isLiked: false,
      },
    ],
    collaborations: [
      { brand: "Nike", project: "Summer Campaign 2024", image: "/placeholder.svg?height=100&width=100&text=Nike" },
      {
        brand: "Coca-Cola",
        project: "Holiday Commercial",
        image: "/placeholder.svg?height=100&width=100&text=Coca-Cola",
      },
      { brand: "Apple", project: "Product Photography", image: "/placeholder.svg?height=100&width=100&text=Apple" },
    ],
    brandDeals: [
      { brand: "Canon", type: "Equipment Partnership", status: "Active" },
      { brand: "Adobe", type: "Software Ambassador", status: "Active" },
      { brand: "Manfrotto", type: "Tripod Sponsor", status: "Completed" },
    ],
    packages: [
      {
        name: "Basic Portrait Session",
        price: 150,
        duration: "1 hour",
        deliverables: ["10 edited photos", "Online gallery", "Print release"],
        turnaround: "3-5 days",
      },
      {
        name: "Wedding Photography",
        price: 1200,
        duration: "8 hours",
        deliverables: ["300+ edited photos", "Online gallery", "USB drive", "Print release"],
        turnaround: "2-3 weeks",
      },
      {
        name: "Commercial Shoot",
        price: 500,
        duration: "Half day",
        deliverables: ["50 edited photos", "Commercial license", "Raw files"],
        turnaround: "1 week",
      },
    ],
  },
  {
    id: 2,
    name: "Alex Chen",
    username: "@alexdesigns",
    category: "UI/UX Design",
    rating: 4.8,
    reviews: 89,
    avatar: "/placeholder.svg?height=150&width=150&text=AC",
    coverImage: "/placeholder.svg?height=400&width=800&text=Design+Cover",
    isVerified: true,
    location: "San Francisco, USA",
    startingPrice: 200,
    tags: ["Mobile", "Web", "Branding"],
    followers: "8.3K",
    following: "2.1K",
    bio: "Senior UI/UX Designer with 6+ years creating intuitive digital experiences. I specialize in mobile apps, web platforms, and brand identity design that converts users into customers.",
    joinedDate: "January 2021",
    responseTime: "Within 4 hours",
    languages: ["English", "Mandarin"],
    socialLinks: {
      dribbble: "https://dribbble.com/alexdesigns",
      behance: "https://behance.net/alexchen",
      website: "https://alexchendesign.com",
      linkedin: "https://linkedin.com/in/alexchen",
    },
    portfolio: [
      {
        id: 1,
        title: "E-commerce Mobile App",
        image: "/placeholder.svg?height=300&width=400&text=Mobile+App+Design",
        category: "Mobile",
        likes: 445,
        isLiked: false,
      },
      {
        id: 2,
        title: "SaaS Dashboard",
        image: "/placeholder.svg?height=300&width=400&text=Dashboard+Design",
        category: "Web",
        likes: 378,
        isLiked: true,
      },
      {
        id: 3,
        title: "Brand Identity System",
        image: "/placeholder.svg?height=300&width=400&text=Brand+Identity",
        category: "Branding",
        likes: 289,
        isLiked: false,
      },
      {
        id: 4,
        title: "Fintech App UI",
        image: "/placeholder.svg?height=300&width=400&text=Fintech+App",
        category: "Mobile",
        likes: 512,
        isLiked: true,
      },
    ],
    collaborations: [
      { brand: "Spotify", project: "Music App Redesign", image: "/placeholder.svg?height=100&width=100&text=Spotify" },
      { brand: "Airbnb", project: "Host Dashboard", image: "/placeholder.svg?height=100&width=100&text=Airbnb" },
    ],
    brandDeals: [
      { brand: "Figma", type: "Design Tool Ambassador", status: "Active" },
      { brand: "Adobe", type: "Creative Suite Partner", status: "Active" },
    ],
    packages: [
      {
        name: "Mobile App Design",
        price: 800,
        duration: "2 weeks",
        deliverables: ["Complete UI kit", "Prototype", "Design system", "Developer handoff"],
        turnaround: "2-3 weeks",
      },
      {
        name: "Website Redesign",
        price: 1500,
        duration: "3 weeks",
        deliverables: ["Wireframes", "High-fidelity designs", "Responsive layouts", "Style guide"],
        turnaround: "3-4 weeks",
      },
    ],
  },
  {
    id: 3,
    name: "Maria Rodriguez",
    username: "@maria_creates",
    category: "Content Creation",
    rating: 4.9,
    reviews: 156,
    avatar: "/imaages/creator3.jpg",
    coverImage: "/images/creator3.jpg",
    isVerified: true,
    location: "Los Angeles, USA",
    startingPrice: 100,
    tags: ["Social Media", "Video", "Copywriting"],
    followers: "25.1K",
    following: "3.4K",
    bio: "Creative content strategist and social media expert. I help brands tell their story through engaging video content, compelling copy, and strategic social media campaigns.",
    joinedDate: "June 2019",
    responseTime: "Within 1 hour",
    languages: ["English", "Spanish", "Portuguese"],
    socialLinks: {
      instagram: "https://instagram.com/maria_creates",
      tiktok: "https://tiktok.com/@maria_creates",
      youtube: "https://youtube.com/mariacreates",
      twitter: "https://twitter.com/maria_creates",
    },
    portfolio: [
      {
        id: 1,
        title: "Brand Campaign Video",
        image: "/placeholder.svg?height=300&width=400&text=Brand+Video",
        category: "Video",
        likes: 678,
        isLiked: true,
      },
      {
        id: 2,
        title: "Social Media Strategy",
        image: "/placeholder.svg?height=300&width=400&text=Social+Strategy",
        category: "Social Media",
        likes: 423,
        isLiked: false,
      },
      {
        id: 3,
        title: "Product Launch Content",
        image: "/placeholder.svg?height=300&width=400&text=Product+Launch",
        category: "Content",
        likes: 567,
        isLiked: true,
      },
    ],
    collaborations: [
      {
        brand: "Netflix",
        project: "Series Promotion Campaign",
        image: "/placeholder.svg?height=100&width=100&text=Netflix",
      },
      {
        brand: "Sephora",
        project: "Beauty Content Series",
        image: "/placeholder.svg?height=100&width=100&text=Sephora",
      },
    ],
    brandDeals: [
      { brand: "Canon", type: "Camera Equipment", status: "Active" },
      { brand: "Adobe", type: "Creative Cloud", status: "Active" },
    ],
    packages: [
      {
        name: "Social Media Package",
        price: 500,
        duration: "1 week",
        deliverables: ["10 posts", "Captions", "Hashtag strategy", "Content calendar"],
        turnaround: "1 week",
      },
      {
        name: "Video Content Creation",
        price: 800,
        duration: "2 weeks",
        deliverables: ["3 videos", "Scripts", "Editing", "Thumbnails"],
        turnaround: "2 weeks",
      },
    ],
  },
  {
    id: 4,
    name: "David Kim",
    username: "@davidfilms",
    category: "Video Production",
    rating: 4.7,
    reviews: 73,
    avatar: "/placeholder.svg?height=150&width=150&text=DK",
    coverImage: "/placeholder.svg?height=400&width=800&text=Video+Production+Cover",
    isVerified: false,
    location: "Austin, USA",
    startingPrice: 300,
    tags: ["Commercial", "Documentary", "Music Videos"],
    followers: "5.7K",
    following: "1.8K",
    bio: "Filmmaker and video producer specializing in commercial content, documentaries, and music videos. I bring stories to life through cinematic visuals and compelling narratives.",
    joinedDate: "September 2021",
    responseTime: "Within 6 hours",
    languages: ["English", "Korean"],
    socialLinks: {
      vimeo: "https://vimeo.com/davidfilms",
      youtube: "https://youtube.com/davidkimfilms",
      website: "https://davidkimfilms.com",
      instagram: "https://instagram.com/davidfilms",
    },
    portfolio: [
      {
        id: 1,
        title: "Tech Startup Commercial",
        image: "/placeholder.svg?height=300&width=400&text=Commercial+Video",
        category: "Commercial",
        likes: 234,
        isLiked: false,
      },
      {
        id: 2,
        title: "Music Video Production",
        image: "/placeholder.svg?height=300&width=400&text=Music+Video",
        category: "Music Video",
        likes: 345,
        isLiked: true,
      },
      {
        id: 3,
        title: "Documentary Short",
        image: "/placeholder.svg?height=300&width=400&text=Documentary",
        category: "Documentary",
        likes: 189,
        isLiked: false,
      },
    ],
    collaborations: [
      { brand: "Tesla", project: "Product Launch Video", image: "/placeholder.svg?height=100&width=100&text=Tesla" },
      { brand: "Spotify", project: "Artist Documentary", image: "/placeholder.svg?height=100&width=100&text=Spotify" },
    ],
    brandDeals: [
      { brand: "Sony", type: "Camera Equipment", status: "Active" },
      { brand: "DJI", type: "Drone Partnership", status: "Completed" },
    ],
    packages: [
      {
        name: "Commercial Video",
        price: 1500,
        duration: "1 week",
        deliverables: ["30-60 second video", "Raw footage", "Color grading", "Sound design"],
        turnaround: "1-2 weeks",
      },
      {
        name: "Music Video",
        price: 2000,
        duration: "2 weeks",
        deliverables: ["Full music video", "Behind the scenes", "Multiple cuts", "Color correction"],
        turnaround: "2-3 weeks",
      },
    ],
  },
  {
    id: 5,
    name: "Emma Thompson",
    username: "@emma_writes",
    category: "Copywriting",
    rating: 4.8,
    reviews: 94,
    avatar: "/placeholder.svg?height=150&width=150&text=ET",
    coverImage: "/placeholder.svg?height=400&width=800&text=Writing+Cover",
    isVerified: true,
    location: "London, UK",
    startingPrice: 80,
    tags: ["Marketing", "Blog Posts", "Email"],
    followers: "6.9K",
    following: "2.3K",
    bio: "Professional copywriter and content strategist with expertise in marketing copy, blog content, and email campaigns. I craft words that convert and engage your audience.",
    joinedDate: "April 2020",
    responseTime: "Within 3 hours",
    languages: ["English", "French"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/emmathompson",
      twitter: "https://twitter.com/emma_writes",
      website: "https://emmathompsonwrites.com",
      medium: "https://medium.com/@emma_writes",
    },
    portfolio: [
      {
        id: 1,
        title: "SaaS Landing Page Copy",
        image: "/placeholder.svg?height=300&width=400&text=Landing+Page+Copy",
        category: "Marketing",
        likes: 156,
        isLiked: true,
      },
      {
        id: 2,
        title: "Email Campaign Series",
        image: "/placeholder.svg?height=300&width=400&text=Email+Campaign",
        category: "Email",
        likes: 123,
        isLiked: false,
      },
      {
        id: 3,
        title: "Blog Content Strategy",
        image: "/placeholder.svg?height=300&width=400&text=Blog+Content",
        category: "Blog",
        likes: 198,
        isLiked: true,
      },
    ],
    collaborations: [
      {
        brand: "HubSpot",
        project: "Marketing Blog Series",
        image: "/placeholder.svg?height=100&width=100&text=HubSpot",
      },
      { brand: "Mailchimp", project: "Email Templates", image: "/placeholder.svg?height=100&width=100&text=Mailchimp" },
    ],
    brandDeals: [
      { brand: "Grammarly", type: "Writing Tool Partnership", status: "Active" },
      { brand: "Notion", type: "Productivity Ambassador", status: "Active" },
    ],
    packages: [
      {
        name: "Website Copy",
        price: 400,
        duration: "3 days",
        deliverables: ["Homepage copy", "About page", "Service pages", "CTA optimization"],
        turnaround: "3-5 days",
      },
      {
        name: "Email Campaign",
        price: 300,
        duration: "1 week",
        deliverables: ["5 email sequence", "Subject lines", "A/B test variants", "Performance tracking"],
        turnaround: "1 week",
      },
    ],
  },
  {
    id: 6,
    name: "James Wilson",
    username: "@jamesgraphics",
    category: "Graphic Design",
    rating: 4.6,
    reviews: 112,
    avatar: "/placeholder.svg?height=150&width=150&text=JW",
    coverImage: "/placeholder.svg?height=400&width=800&text=Graphic+Design+Cover",
    isVerified: true,
    location: "Toronto, Canada",
    startingPrice: 120,
    tags: ["Logo", "Print", "Illustration"],
    followers: "9.2K",
    following: "1.9K",
    bio: "Creative graphic designer specializing in brand identity, print design, and custom illustrations. I help businesses stand out with memorable visual designs.",
    joinedDate: "August 2019",
    responseTime: "Within 4 hours",
    languages: ["English", "French"],
    socialLinks: {
      behance: "https://behance.net/jameswilson",
      dribbble: "https://dribbble.com/jamesgraphics",
      instagram: "https://instagram.com/jamesgraphics",
      website: "https://jameswilsondesign.com",
    },
    portfolio: [
      {
        id: 1,
        title: "Restaurant Brand Identity",
        image: "/placeholder.svg?height=300&width=400&text=Restaurant+Branding",
        category: "Branding",
        likes: 267,
        isLiked: false,
      },
      {
        id: 2,
        title: "Magazine Layout Design",
        image: "/placeholder.svg?height=300&width=400&text=Magazine+Layout",
        category: "Print",
        likes: 189,
        isLiked: true,
      },
      {
        id: 3,
        title: "Custom Illustrations",
        image: "/placeholder.svg?height=300&width=400&text=Illustrations",
        category: "Illustration",
        likes: 345,
        isLiked: false,
      },
    ],
    collaborations: [
      {
        brand: "Starbucks",
        project: "Seasonal Cup Design",
        image: "/placeholder.svg?height=100&width=100&text=Starbucks",
      },
      { brand: "Nike", project: "Poster Campaign", image: "/placeholder.svg?height=100&width=100&text=Nike" },
    ],
    brandDeals: [
      { brand: "Adobe", type: "Creative Suite Partner", status: "Active" },
      { brand: "Wacom", type: "Tablet Sponsor", status: "Active" },
    ],
    packages: [
      {
        name: "Logo Design",
        price: 300,
        duration: "5 days",
        deliverables: ["3 logo concepts", "Final files", "Brand guidelines", "Social media kit"],
        turnaround: "5-7 days",
      },
      {
        name: "Print Design Package",
        price: 500,
        duration: "1 week",
        deliverables: ["Business cards", "Letterhead", "Brochure", "Print-ready files"],
        turnaround: "1-2 weeks",
      },
    ],
  },
]

interface CreatorPageProps {
  params: {
    id: string
  }
}

export default function CreatorPage({ params }: CreatorPageProps) {
  const creator = creators.find((c) => c.id === Number.parseInt(params.id))

  if (!creator) {
    notFound()
  }

  return <CreatorProfile creator={creator} />
}
